package ackinv

import (
	"fmt"
	"sort"
	"strings"

	"github.com/edgarsilva948/ackrocheck/internal/policy"
)

// CoverageReport renders docs/coverage.md: which ACK services and kinds have
// at least one built-in control, and which are uncovered. The output is
// deterministic and contains no timestamps so regenerating without upstream
// or control changes produces no diff.
func CoverageReport(inv *Inventory, policies []policy.Policy) string {
	controlsByKind := map[string][]string{} // "group/kind" (lower) -> control IDs
	for _, p := range policies {
		for _, g := range p.Match.APIGroups {
			for _, k := range p.Match.Kinds {
				key := strings.ToLower(g) + "/" + strings.ToLower(k)
				controlsByKind[key] = append(controlsByKind[key], p.ID)
			}
		}
	}

	var b strings.Builder
	b.WriteString("# ACK coverage\n\n")
	b.WriteString("Generated by `go run ./tools/ack-inventory` from " +
		"[`mappings/ack/inventory.json`](../mappings/ack/inventory.json). " +
		"Do not edit by hand.\n\n")

	totalKinds, coveredKinds := 0, 0
	servicesWithControls := 0
	type row struct {
		svc      *Service
		covered  int
		total    int
		controls map[string]bool
	}
	rows := make([]row, 0, len(inv.Services))
	for si := range inv.Services {
		svc := &inv.Services[si]
		r := row{svc: svc, controls: map[string]bool{}}
		for _, k := range svc.Kinds {
			r.total++
			key := strings.ToLower(k.Group) + "/" + strings.ToLower(k.Kind)
			ids := controlsByKind[key]
			if len(ids) > 0 {
				r.covered++
				for _, id := range ids {
					r.controls[id] = true
				}
			}
		}
		totalKinds += r.total
		coveredKinds += r.covered
		if len(r.controls) > 0 {
			servicesWithControls++
		}
		rows = append(rows, r)
	}

	fmt.Fprintf(&b, "**Summary:** %d/%d services have at least one control; %d/%d kinds covered.\n\n",
		servicesWithControls, len(inv.Services), coveredKinds, totalKinds)

	b.WriteString("| Service | Release | Kinds | Covered | Controls |\n")
	b.WriteString("|---|---|---:|---:|---|\n")
	for _, r := range rows {
		ids := make([]string, 0, len(r.controls))
		for id := range r.controls {
			ids = append(ids, id)
		}
		sort.Strings(ids)
		controlsCell := "—"
		if len(ids) > 0 {
			controlsCell = strings.Join(ids, ", ")
		}
		fmt.Fprintf(&b, "| %s | %s | %d | %d | %s |\n",
			r.svc.Name, orDash(r.svc.Release), r.total, r.covered, controlsCell)
	}

	b.WriteString("\n## Uncovered kinds\n\n")
	b.WriteString("Kinds with no matching control, grouped by service:\n\n")
	any := false
	for _, r := range rows {
		var uncovered []string
		for _, k := range r.svc.Kinds {
			key := strings.ToLower(k.Group) + "/" + strings.ToLower(k.Kind)
			if len(controlsByKind[key]) == 0 {
				uncovered = append(uncovered, k.Kind)
			}
		}
		if len(uncovered) == 0 {
			continue
		}
		any = true
		fmt.Fprintf(&b, "- **%s**: %s\n", r.svc.Name, strings.Join(uncovered, ", "))
	}
	if !any {
		b.WriteString("(none)\n")
	}
	return b.String()
}

func orDash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
